# Generated by Django 4.1.5 on 2023-01-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksyshev', '0002_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_load', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('image', models.ImageField(default=None, upload_to='static/collage/')),
            ],
        ),
    ]
