# Generated by Django 4.1.5 on 2023-01-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksyshev', '0003_collage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_load', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('video', models.FileField(default=None, upload_to='static/video/')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.AlterModelOptions(
            name='collage',
            options={'verbose_name': 'Коллаж', 'verbose_name_plural': 'Коллажи'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Фотку', 'verbose_name_plural': 'Фотки'},
        ),
    ]
