# Generated by Django 4.1.5 on 2023-02-06 07:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ksyshev', '0005_clientuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, region=None, unique=True),
        ),
    ]
