# Generated by Django 4.1.5 on 2023-02-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksyshev', '0006_alter_clientuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
    ]
