# Generated by Django 4.1.5 on 2023-02-06 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ksyshev', '0007_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ip',
            options={'verbose_name': 'Посещение', 'verbose_name_plural': 'Посещения'},
        ),
        migrations.AddField(
            model_name='ip',
            name='count_visit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ip',
            name='date_visit',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата посещения'),
            preserve_default=False,
        ),
    ]
