# Generated by Django 4.1.5 on 2023-02-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksyshev', '0008_alter_ip_options_ip_count_visit_ip_date_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='count_visit',
        ),
    ]
