# Generated by Django 4.1.5 on 2023-02-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksyshev', '0009_remove_ip_count_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='date_visit',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата посещения'),
        ),
    ]
